% This script is written and read by pdetool and should NOT be edited.
% There are two recommended alternatives:
% 1) Export the required variables from pdetool and create a MATLAB script
%    to perform operations on these.
% 2) Define the problem completely using a MATLAB script. See
%    https://www.mathworks.com/help/pde/examples.html for examples
%    of this approach.
function pdemodel
[pde_fig,ax]=pdeinit;
pdetool('appl_cb',5);
set(ax,'DataAspectRatio',[1 1 1]);
set(ax,'PlotBoxAspectRatio',[1.5 1 1]);
set(ax,'XLim',[-1.5 1.5]);
set(ax,'YLim',[-1 1]);
set(ax,'XTickMode','auto');
set(ax,'YTickMode','auto');

% Geometry description:
pdecirc(0,0,0.25,'C1');
pdecirc(0,0,0.55000000000000004,'C2');
set(findobj(get(pde_fig,'Children'),'Tag','PDEEval'),'String','C2-C1')

% Boundary conditions:
pdetool('changemode',0)
pdesetbd(8,...
'dir',...
1,...
'1',...
'-3*(x.^2+y.^2)/2')
pdesetbd(7,...
'dir',...
1,...
'1',...
'-3*(x.^2+y.^2)/2')
pdesetbd(6,...
'dir',...
1,...
'1',...
'-3*(x.^2+y.^2)/2')
pdesetbd(5,...
'dir',...
1,...
'1',...
'-3*(x.^2+y.^2)/2')
pdesetbd(4,...
'dir',...
1,...
'1',...
'-3*(x.^2+y.^2)/2')
pdesetbd(3,...
'dir',...
1,...
'1',...
'-3*(x.^2+y.^2)/2')
pdesetbd(2,...
'dir',...
1,...
'1',...
'-3*(x.^2+y.^2)/2')
pdesetbd(1,...
'dir',...
1,...
'1',...
'-3*(x.^2+y.^2)/2')

% Mesh generation:
setappdata(pde_fig,'Hgrad',1.3);
setappdata(pde_fig,'refinemethod','regular');
setappdata(pde_fig,'jiggle',char('on','mean',''));
setappdata(pde_fig,'MesherVersion','preR2013a');
pdetool('initmesh')

% PDE coefficients:
pdeseteq(1,...
'5.6*8.85e-12',...
'0.0',...
'6*5.6*8.85e-12',...
'1.0',...
'0:10',...
'0.0',...
'0.0',...
'[0 100]')
setappdata(pde_fig,'currparam',...
['5.6*8.85e-12  ';...
'6*5.6*8.85e-12'])

% Solve parameters:
setappdata(pde_fig,'solveparam',...
char('0','1000','10','pdeadworst',...
'0.5','longest','0','1E-4','','fixed','Inf'))

% Plotflags and user data strings:
setappdata(pde_fig,'plotflags',[1 1 1 1 1 1 1 1 0 0 0 1 1 1 0 0 0 1]);
setappdata(pde_fig,'colstring','');
setappdata(pde_fig,'arrowstring','');
setappdata(pde_fig,'deformstring','');
setappdata(pde_fig,'heightstring','');

% Solve PDE:
pdetool('solve')
